-- Clean-room baseline for the original single-user workout tracker schema.
--
-- The production project predates the checked-in Supabase migration history.
-- Later migrations therefore harden and extend tables which did not previously
-- exist in a fresh environment. This additive baseline captures the inventoried
-- 2026-07-13 schema so `supabase db reset` and disaster recovery start from the
-- same bigint identities, columns, foreign keys, and owner-only RLS boundary.
-- Existing projects may run this safely: tables and policies are only created
-- when absent, and no existing row is modified.

begin;

set local lock_timeout = '5s';
set local statement_timeout = '30s';

create table if not exists public.exercises (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name text not null default '',
  category text default '',
  muscles text[],
  muscles_secondary text[],
  images text[],
  instructions text[],
  equipment text
);

create table if not exists public.routines (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users (id) on delete cascade,
  name text not null,
  is_preset boolean not null default false,
  created_at timestamptz default now()
);

create table if not exists public.routine_exercises (
  id uuid primary key default gen_random_uuid(),
  routine_id uuid not null references public.routines (id) on delete cascade,
  exercise_id bigint not null references public.exercises (id) on delete restrict,
  sets integer not null,
  reps integer,
  "order" integer not null,
  weight numeric,
  duration_minutes numeric,
  distance numeric,
  set_details jsonb,
  tempo text,
  rest_seconds integer
);

-- Workout and set ownership intentionally has no auth.users foreign key. The
-- live schema retains historical training results after an auth account is
-- removed; RLS and the later composite owner key enforce access and integrity.
create table if not exists public.workouts (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  user_id uuid not null,
  date date not null,
  status text not null default 'in_progress',
  template_id uuid references public.routines (id) on delete set null,
  constraint workouts_status_check
    check (status in ('planned', 'in_progress', 'completed'))
);

create table if not exists public.sets (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  workout_id bigint not null references public.workouts (id) on delete cascade,
  exercise_id bigint not null references public.exercises (id) on delete restrict,
  user_id uuid not null default auth.uid(),
  weight numeric,
  reps integer,
  duration_minutes numeric,
  distance numeric,
  rest_seconds numeric,
  difficulty smallint
);

create table if not exists public.scheduled_workouts (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users (id) on delete cascade,
  routine_id uuid not null references public.routines (id) on delete cascade,
  scheduled_date date not null,
  assigned_by uuid references auth.users (id) on delete set null,
  workout_id bigint references public.workouts (id) on delete set null,
  created_at timestamptz default now()
);

create table if not exists public.body_weights (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users (id) on delete cascade,
  date date not null,
  weight numeric not null,
  created_at timestamptz default now(),
  unique (user_id, date)
);

create table if not exists public.exercise_notes (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users (id) on delete cascade,
  exercise_id bigint not null references public.exercises (id) on delete cascade,
  note text,
  updated_at timestamptz default now(),
  unique (user_id, exercise_id)
);

alter table public.exercises enable row level security;
alter table public.routines enable row level security;
alter table public.routine_exercises enable row level security;
alter table public.workouts enable row level security;
alter table public.sets enable row level security;
alter table public.scheduled_workouts enable row level security;
alter table public.body_weights enable row level security;
alter table public.exercise_notes enable row level security;

-- Policy creation is conditional so this baseline is harmless when replayed
-- against the inventoried live project. Phase 1A replaces the workout, set,
-- routine-exercise update, and exercise policies with their hardened forms.
do $policies$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'exercises'
      and policyname = 'exercises: authenticated read'
  ) then
    execute $ddl$
      create policy "exercises: authenticated read"
        on public.exercises for select to authenticated using (true)
    $ddl$;
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'routines'
      and policyname = 'routines: read presets and own'
  ) then
    execute $ddl$
      create policy "routines: read presets and own"
        on public.routines for select to authenticated
        using (is_preset = true or (select auth.uid()) = user_id)
    $ddl$;
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'routines'
      and policyname = 'routines: users insert their own'
  ) then
    execute $ddl$
      create policy "routines: users insert their own"
        on public.routines for insert to authenticated
        with check ((select auth.uid()) = user_id and is_preset = false)
    $ddl$;
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'routines'
      and policyname = 'routines: users update their own'
  ) then
    execute $ddl$
      create policy "routines: users update their own"
        on public.routines for update to authenticated
        using ((select auth.uid()) = user_id and is_preset = false)
        with check ((select auth.uid()) = user_id and is_preset = false)
    $ddl$;
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'routines'
      and policyname = 'routines: users delete their own'
  ) then
    execute $ddl$
      create policy "routines: users delete their own"
        on public.routines for delete to authenticated
        using ((select auth.uid()) = user_id and is_preset = false)
    $ddl$;
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'routine_exercises'
      and policyname = 'routine_exercises: read own and presets'
  ) then
    execute $ddl$
      create policy "routine_exercises: read own and presets"
        on public.routine_exercises for select to authenticated
        using (exists (
          select 1 from public.routines as routine
          where routine.id = routine_id
            and (routine.is_preset = true or routine.user_id = (select auth.uid()))
        ))
    $ddl$;
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'routine_exercises'
      and policyname = 'routine_exercises: users insert their own'
  ) then
    execute $ddl$
      create policy "routine_exercises: users insert their own"
        on public.routine_exercises for insert to authenticated
        with check (exists (
          select 1 from public.routines as routine
          where routine.id = routine_id
            and routine.user_id = (select auth.uid())
            and routine.is_preset = false
        ))
    $ddl$;
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'routine_exercises'
      and policyname = 'routine_exercises: users update their own'
  ) then
    execute $ddl$
      create policy "routine_exercises: users update their own"
        on public.routine_exercises for update to authenticated
        using (exists (
          select 1 from public.routines as routine
          where routine.id = routine_id
            and routine.user_id = (select auth.uid())
            and routine.is_preset = false
        ))
        with check (exists (
          select 1 from public.routines as routine
          where routine.id = routine_id
            and routine.user_id = (select auth.uid())
            and routine.is_preset = false
        ))
    $ddl$;
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'routine_exercises'
      and policyname = 'routine_exercises: users delete their own'
  ) then
    execute $ddl$
      create policy "routine_exercises: users delete their own"
        on public.routine_exercises for delete to authenticated
        using (exists (
          select 1 from public.routines as routine
          where routine.id = routine_id
            and routine.user_id = (select auth.uid())
            and routine.is_preset = false
        ))
    $ddl$;
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'workouts'
      and policyname = 'workouts: select own'
  ) then
    execute $ddl$
      create policy "workouts: select own" on public.workouts
        for select to authenticated using ((select auth.uid()) = user_id)
    $ddl$;
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'workouts'
      and policyname = 'workouts: insert own'
  ) then
    execute $ddl$
      create policy "workouts: insert own" on public.workouts
        for insert to authenticated with check ((select auth.uid()) = user_id)
    $ddl$;
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'workouts'
      and policyname = 'workouts: update own'
  ) then
    execute $ddl$
      create policy "workouts: update own" on public.workouts
        for update to authenticated
        using ((select auth.uid()) = user_id)
        with check ((select auth.uid()) = user_id)
    $ddl$;
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'workouts'
      and policyname = 'workouts: delete own'
  ) then
    execute $ddl$
      create policy "workouts: delete own" on public.workouts
        for delete to authenticated using ((select auth.uid()) = user_id)
    $ddl$;
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'sets'
      and policyname = 'Users can manage their own sets'
  ) then
    execute $ddl$
      create policy "Users can manage their own sets" on public.sets
        for all to authenticated
        using ((select auth.uid()) = user_id)
        with check ((select auth.uid()) = user_id)
    $ddl$;
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'scheduled_workouts'
      and policyname = 'scheduled_workouts: users select their own'
  ) then
    execute $ddl$
      create policy "scheduled_workouts: users select their own"
        on public.scheduled_workouts for select to authenticated
        using ((select auth.uid()) = user_id)
    $ddl$;
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'scheduled_workouts'
      and policyname = 'scheduled_workouts: users insert their own'
  ) then
    execute $ddl$
      create policy "scheduled_workouts: users insert their own"
        on public.scheduled_workouts for insert to authenticated
        with check ((select auth.uid()) = user_id)
    $ddl$;
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'scheduled_workouts'
      and policyname = 'scheduled_workouts: users update their own'
  ) then
    execute $ddl$
      create policy "scheduled_workouts: users update their own"
        on public.scheduled_workouts for update to authenticated
        using ((select auth.uid()) = user_id)
        with check ((select auth.uid()) = user_id)
    $ddl$;
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'scheduled_workouts'
      and policyname = 'scheduled_workouts: users delete their own'
  ) then
    execute $ddl$
      create policy "scheduled_workouts: users delete their own"
        on public.scheduled_workouts for delete to authenticated
        using ((select auth.uid()) = user_id)
    $ddl$;
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'body_weights'
      and policyname = 'body_weights: users select their own'
  ) then
    execute $ddl$
      create policy "body_weights: users select their own"
        on public.body_weights for select to authenticated
        using ((select auth.uid()) = user_id)
    $ddl$;
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'body_weights'
      and policyname = 'body_weights: users insert their own'
  ) then
    execute $ddl$
      create policy "body_weights: users insert their own"
        on public.body_weights for insert to authenticated
        with check ((select auth.uid()) = user_id)
    $ddl$;
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'body_weights'
      and policyname = 'body_weights: users update their own'
  ) then
    execute $ddl$
      create policy "body_weights: users update their own"
        on public.body_weights for update to authenticated
        using ((select auth.uid()) = user_id)
        with check ((select auth.uid()) = user_id)
    $ddl$;
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'body_weights'
      and policyname = 'body_weights: users delete their own'
  ) then
    execute $ddl$
      create policy "body_weights: users delete their own"
        on public.body_weights for delete to authenticated
        using ((select auth.uid()) = user_id)
    $ddl$;
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'exercise_notes'
      and policyname = 'exercise_notes: select own'
  ) then
    execute $ddl$
      create policy "exercise_notes: select own" on public.exercise_notes
        for select to authenticated using ((select auth.uid()) = user_id)
    $ddl$;
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'exercise_notes'
      and policyname = 'exercise_notes: insert own'
  ) then
    execute $ddl$
      create policy "exercise_notes: insert own" on public.exercise_notes
        for insert to authenticated with check ((select auth.uid()) = user_id)
    $ddl$;
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'exercise_notes'
      and policyname = 'exercise_notes: update own'
  ) then
    execute $ddl$
      create policy "exercise_notes: update own" on public.exercise_notes
        for update to authenticated
        using ((select auth.uid()) = user_id)
        with check ((select auth.uid()) = user_id)
    $ddl$;
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'exercise_notes'
      and policyname = 'exercise_notes: delete own'
  ) then
    execute $ddl$
      create policy "exercise_notes: delete own" on public.exercise_notes
        for delete to authenticated using ((select auth.uid()) = user_id)
    $ddl$;
  end if;
end
$policies$;

notify pgrst, 'reload schema';

commit;
